// fileSystem
export const CHANGE_CURRENT_FILEPATH = 'CHANGE_CURRENT_FILEPATH'
export const UPDATE_CHECKED_FILES_WITH_FILEPATH = 'UPDATE_CHECKED_FILES_WITH_FILEPATH' // multiple select files
export const UPDATE_CHECKED_FILE_WITH_FILEPATH = 'UPDATE_CHECKED_FILE_WITH_FILEPATH' // select one file
export const CLEAR_CHECKED_FILES_WITH_FILEPATH = 'CLEAR_CHECKED_FILES_WITH_FILEPATH'
