// File System
export const CHANGE_CURRENT_FILEPATH = 'CHANGE_CURRENT_FILEPATH'
export const UPDATE_CHECKED_FILES_WITH_FILEPATH = 'UPDATE_CHECKED_FILES_WITH_FILEPATH' // multiple select files
export const UPDATE_CHECKED_FILE_WITH_FILEPATH = 'UPDATE_CHECKED_FILE_WITH_FILEPATH' // select one file
export const CLEAR_CHECKED_FILES_WITH_FILEPATH = 'CLEAR_CHECKED_FILES_WITH_FILEPATH'
// Task Manager
export const ADD_PROCESS_WITH_APP = 'ADD_PROCESS_WITH_APP'
export const ADD_CHILD_PROCESS_WITH_APP = 'ADD_CHILD_PROCESS_WITH_APP'
