// fileSystem
export const CHANGE_CURRENT_FILEPATH = 'CHANGE_CURRENT_FILEPATH'
export const UPDATE_CHECKED_FILES_WITH_FILEPATH = 'UPDATE_CHECKED_FILES_WITH_FILEPATH'
export const CLEAR_CHECKED_FILES_WITH_FILEPATH = 'CLEAR_CHECKED_FILES_WITH_FILEPATH'
